Add Server rendering to react project
bandax/Movies.ReactJS pull request #11
Opened 2020-10-29 07:19 UTC by bandax

I have this issue: 

ReferenceError: window is not defined
    at eval (webpack:///./src/components/App.tsx?:34:1)
    at Object../src/components/App.tsx (C:\Users\Luis_Banda\Documents\React\Mentoring\Movies.ReactJS\public\js\serverRenderer.js:122:1)
    at __webpack_require__ (C:\Users\Luis_Banda\Documents\React\Mentoring\Movies.ReactJS\public\js\serverRenderer.js:21:30)
    at eval (webpack:///./src/serverRenderer.tsx?:9:13)
    at Object../src/serverRenderer.tsx (C:\Users\Luis_Banda\Documents\React\Mentoring\Movies.ReactJS\public\js\serverRenderer.js:312:1)
    at __webpack_require__ (C:\Users\Luis_Banda\Documents\React\Mentoring\Movies.ReactJS\public\js\serverRenderer.js:21:30)
    at C:\Users\Luis_Banda\Documents\React\Mentoring\Movies.ReactJS\public\js\serverRenderer.js:85:18
    at Object.<anonymous> (C:\Users\Luis_Banda\Documents\React\Mentoring\Movies.ReactJS\public\js\serverRenderer.js:88:10)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at requireFromString (C:\Users\Luis_Banda\Documents\React\Mentoring\Movies.ReactJS\node_modules\require-from-string\index.js:28:4)

2020-10-30 21:38 UTC, endiny requested changes

2020-10-30 21:38 UTC, endiny commented on src/client.tsx
> +}
I think you can join it with another `interface Window`

2020-10-30 21:38 UTC, endiny commented on src/components/AddMovie/AddMovie.tsx
> +      /> */}
Please don't keep commented code in VCS. It can be retrieved in previous commits

2020-11-04 06:28 UTC, bandax commented on src/client.tsx
> +}
you mean change this to its own file?

2020-11-05 09:14 UTC, endiny commented on src/client.tsx
> +}
you have two `declare global`. Merge them onto one statement\
```
declare global {
  interface Window {
  __REDUX_DEVTOOLS_EXTENSION_COMPOSE__?: typeof compose;
    PRELOADED_STATE: any;
  }
}

2020-11-05 09:15 UTC, merged