Add prettier configuration to format code automatically
bandax/Movies.ReactJS pull request #5
Opened 2020-09-04 04:00 UTC by bandax

2020-09-14 22:40 UTC, endiny requested changes

2020-09-14 22:40 UTC, endiny commented on src/components/AddMovieWindow/AddMovieWindow.tsx
> +        <a
make it a button

2020-09-14 22:40 UTC, endiny commented on src/components/App.scss
> +}
optional: You can use SCSS's loops for doing that

2020-09-15 01:52 UTC, bandax commented on src/components/App.scss
> +}
done

2020-09-15 01:57 UTC, bandax commented on src/components/AddMovieWindow/AddMovieWindow.tsx
> +        <a
done

2020-09-17 20:27 UTC, merged