Task 6 Implement redux actions
bandax/Movies.ReactJS pull request #6
Opened 2020-09-21 05:30 UTC by bandax

2020-09-23 23:23 UTC, endiny requested changes
Fix the formatting and quotes

2020-09-23 23:23 UTC, endiny commented on src/components/AddMovie/AddMovie.tsx
> +const mapState = (state: RootState) => ({
**Optional**: it's a common practice to call these functions `mapStateToProps` and `mapDispatchToProps`

2020-09-23 23:23 UTC, endiny commented on src/components/AddMovie/AddMovie.tsx
> +type Props = PropsFromRedux;
`type Props = ConnectedProps<typeof connector>`?

2020-09-23 23:23 UTC, endiny commented on src/components/AddMovie/AddMovie.tsx
> +        onHandleAddMovieSubmit={handleSubmitAddMovie}
Optional: on and Handle look like synonims. I'd suggest to name such methods like `onAddMovieSubmit`

2020-09-23 23:23 UTC, endiny commented on src/components/AddMovie/AddMovie.tsx
> +export default connector(AddMovie);
Instead of declaring `const connector` you can just write
`export default connect(mapStateToProps, mapDispatchToProps)(AddMovie)`

2020-09-23 23:23 UTC, endiny commented on src/components/AddMovie/thunks.ts
> +    const response = await fetch("http://localhost:4000/movies", {
I'd suggest to move out network logic to the separate class like `NetworkService` which will have methods like `.post` `.get` and so on.

Optional: make those methods use generics

2020-09-23 23:23 UTC, endiny commented on src/components/AddMovieWindow/AddMovieWindow.tsx
> +    movieId: props.movie?.id ?? 0,
According to your props type movie can't be null or undefined. Either modify typings or discard optional chaining

2020-09-23 23:23 UTC, endiny commented on src/components/AddMovieWindow/AddMovieWindow.tsx
> +  console.log(values);
Don't leave console.logs unless they are really needed

2020-09-23 23:23 UTC, endiny commented on src/components/App.scss
> +// @for $i from 1 to 13 {
what's happened to that?

2020-09-23 23:23 UTC, endiny commented on src/store/movie/reducers.ts
> +        movies: state.movies.concat(action.movieToAdd),
Use ES6 features: `[...state.movies, action.movieToAdd]`

2020-09-23 23:23 UTC, endiny commented on src/store/movie/reducers.ts
> +      });
You can make a copy of the array and assign to the index:
```
const newMovies = [...state.movies];
newMovies[index] = action.movieToUpdate;
```

2020-09-23 23:23 UTC, endiny commented on src/store/movie/reducers.ts
> +}
```
if (...) {
  return 1;
} else if (...) {
  return -1;
} else {
  return 0;
}

2020-09-26 01:56 UTC, bandax commented on src/components/AddMovie/AddMovie.tsx
> +const mapState = (state: RootState) => ({
@endiny what do you mean with fix formatting and quotes?

2020-09-26 02:25 UTC, bandax commented on src/components/AddMovie/AddMovie.tsx
> +type Props = PropsFromRedux;
It allows me to define props from connector and used in the:
const AddMovie: React.FunctionComponent<PropsFromRedux>

2020-09-26 04:53 UTC, bandax commented on src/components/AddMovieWindow/AddMovieWindow.tsx
> +    movieId: props.movie?.id ?? 0,
I specified this in the MovieState:
export interface MovieState {
  movie?: IMovieData;
  movies: IMovieData[];
  loading: boolean;
  errorMessage: string;
}

2020-09-26 04:53 UTC, bandax commented on src/components/AddMovieWindow/AddMovieWindow.tsx
> +    movieId: props.movie?.id ?? 0,
but I modified the interface movie property anyway

2020-09-26 04:54 UTC, bandax commented on src/components/App.scss
> +// @for $i from 1 to 13 {
for some reason my for loop did not work to add that style dynamically. do you see something wrong?

2020-09-26 05:08 UTC, bandax commented on src/components/AddMovie/AddMovie.tsx
> +type Props = PropsFromRedux;
fixed using the type syntaxis:
type Props = ReturnType<typeof mapStateToProps> &
  ReturnType<typeof mapDispatchToProps>;

2020-09-26 05:09 UTC, bandax commented on src/components/AddMovie/AddMovie.tsx
> +const mapState = (state: RootState) => ({
done changed names to mapStateToProps and mapDispatchToProps

2020-09-26 05:11 UTC, bandax commented on src/components/AddMovie/AddMovie.tsx
> +        onHandleAddMovieSubmit={handleSubmitAddMovie}
done

2020-09-26 05:12 UTC, bandax commented on src/components/AddMovie/AddMovie.tsx
> +export default connector(AddMovie);
done

2020-09-26 05:13 UTC, bandax commented on src/components/AddMovie/thunks.ts
> +    const response = await fetch("http://localhost:4000/movies", {
created "services/networkService.ts" file to put generic http generic requests

2020-09-26 05:13 UTC, bandax commented on src/components/AddMovieWindow/AddMovieWindow.tsx
> +  console.log(values);
removed

2020-09-26 05:13 UTC, bandax commented on src/store/movie/reducers.ts
> +        movies: state.movies.concat(action.movieToAdd),
done

2020-09-26 05:13 UTC, bandax commented on src/store/movie/reducers.ts
> +}
done

2020-09-26 05:19 UTC, bandax commented on src/store/movie/reducers.ts
> +      });
done

2020-09-28 20:47 UTC, endiny commented on src/components/AddMovie/AddMovie.tsx
> +const mapState = (state: RootState) => ({
Oh, sorry I didn't notice that you switched to the double quotes. Though I recommend going with single quotes

2020-09-28 20:48 UTC, endiny commented on src/components/AddMovie/AddMovie.tsx
> +type Props = PropsFromRedux;
Yes, but in previous version you made like
A = ... then B = A, but as far as A is being used nowhere, I'd suggest to keep B = ..., skipping unnecessary variable

2020-09-28 20:56 UTC, endiny requested changes

2020-09-28 20:56 UTC, endiny commented on src/services/networkService.ts
> +export const postRequest = async (data: INetworkData) => {
As far as you're returning `Promise` you don't have to await for it. You can remove `async/await` here and put them in places where you call these functions.

2020-09-28 20:56 UTC, endiny commented on src/store/index.ts
> +  undefined,
Why is it needed?

2020-09-28 21:24 UTC, endiny commented on src/store/movie/constants.ts
> +export const FILTER_BY_RELEASE_DATE_AND_RATING =
I think all this actions can be stored in enums

2020-09-29 17:30 UTC, bandax commented on src/components/AddMovie/AddMovie.tsx
> +const mapState = (state: RootState) => ({
I changed all files to use single quotes instead.

2020-09-29 17:30 UTC, bandax commented on src/components/AddMovie/AddMovie.tsx
> +type Props = PropsFromRedux;
Yes, that's reason I changed to use the props as single variable

2020-09-29 17:31 UTC, bandax commented on src/components/App.scss
> +// @for $i from 1 to 13 {
done with loop

2020-09-29 17:31 UTC, bandax commented on src/services/networkService.ts
> +export const postRequest = async (data: INetworkData) => {
removed async and await

2020-09-29 17:31 UTC, bandax commented on src/store/movie/constants.ts
> +export const FILTER_BY_RELEASE_DATE_AND_RATING =
move to enum type

2020-09-29 21:07 UTC, endiny commented on src/store/movie/types.ts
> +  type: constants.LOADING_MOVIES_ERROR;
I think it can be `type: ACTIONS.LOADING_MOVIES_ERROR` so you won't need exporting all those constants beside enum

2020-09-30 19:37 UTC, bandax commented on src/store/movie/types.ts
> +  type: constants.LOADING_MOVIES_ERROR;
done

2020-10-01 17:58 UTC, merged