Task 7: Implement Formik library for add and edit movie
bandax/Movies.ReactJS pull request #7
Opened 2020-10-04 23:52 UTC by bandax

2020-10-05 17:19 UTC, endiny requested changes

2020-10-05 17:19 UTC, endiny commented on src/components/AddMovieWindow/AddMovieWindow.tsx
> +                  {showMovieIdField()}
Technically, user wouldn't compose id by himself. I'd suggest generating the id at service side

2020-10-05 17:19 UTC, endiny commented on src/components/AddMovieWindow/AddMovieWindow.tsx
> +const FormikDatePicker = ({ ...props }) => {
Also, name it `MovieDatePicket` to be consistent with `MovieTextInput`

2020-10-05 17:19 UTC, endiny commented on src/components/AddMovieWindow/AddMovieWindow.tsx
> +const FormikMultiSelect = ({ ...props }) => {
Please, rename it as well

2020-10-05 17:19 UTC, endiny commented on src/components/AddMovieWindow/AddMovieWindow.tsx
> +                  <label className="label-text" htmlFor="releaseDate">
I bet label can be placed into the form component as well

2020-10-05 17:20 UTC, endiny commented on src/components/AddMovieWindow/AddMovieWindow.tsx
>        (clasOption: IClasification) => ({
`clasOption`
typo?

2020-10-06 03:29 UTC, bandax commented on src/components/AddMovieWindow/AddMovieWindow.tsx
> +                  {showMovieIdField()}
This function is to show/hide the movie id input checking if the movie is new to add or edit an existing one

2020-10-06 03:34 UTC, bandax commented on src/components/AddMovieWindow/AddMovieWindow.tsx
>        (clasOption: IClasification) => ({
this is an alias for my map to get each element from the catalog of classification movies

2020-10-06 03:39 UTC, bandax commented on src/components/AddMovieWindow/AddMovieWindow.tsx
> +const FormikDatePicker = ({ ...props }) => {
Created "Shared" folder where I put all the formik controls

2020-10-06 03:39 UTC, bandax commented on src/components/AddMovieWindow/AddMovieWindow.tsx
> +          })}
done

2020-10-06 03:39 UTC, bandax commented on src/components/AddMovieWindow/AddMovieWindow.tsx
> +              vote_count: values.voteCount,
done

2020-10-06 03:40 UTC, bandax commented on src/components/AddMovieWindow/AddMovieWindow.tsx
> +const FormikDatePicker = ({ ...props }) => {
rename using Formik- prefix

2020-10-06 03:40 UTC, bandax commented on src/components/AddMovieWindow/AddMovieWindow.tsx
> +const FormikMultiSelect = ({ ...props }) => {
rename using Formik- prefix

2020-10-06 03:40 UTC, bandax commented on src/components/AddMovieWindow/AddMovieWindow.tsx
> +                  <label className="label-text" htmlFor="releaseDate">
Moved to the component

2020-10-07 18:56 UTC, endiny commented on src/components/AddMovieWindow/AddMovieWindow.tsx
>        (clasOption: IClasification) => ({
I see
optional: it's cla_ss_ification

2020-10-07 19:05 UTC, endiny commented on src/components/AddMovieWindow/AddMovieWindow.tsx
> +                  {showMovieIdField()}
But as far as I got it shows the input. If id is not supposed to be edited, please either make input disabled or show id in some other element like span

2020-10-07 19:05 UTC, endiny commented on src/components/AddMovieWindow/AddMovieWindow.tsx
> +          validationSchema={Yup.object(validations)}
Move `Yup.object` to `validations` declaration as well

2020-10-07 20:31 UTC, merged